import manifest from "../data/audio-manifest.json";
import { getCleanSlug } from "./content";
import type { Locale } from "../i18n/config";

export type PostAudio = {
  src: string;
  durationSeconds: number;
  bytes: number;
};

type ManifestEntry = {
  hash: string;
  voice: string;
  file: string;
  durationSeconds: number;
  bytes: number;
  chars: number;
  generatedAt: string;
};

const entries = manifest as Record<string, ManifestEntry>;

/** Audio narration for a post, generated by scripts/audio/generate.mjs. */
export function getPostAudio(
  slug: string,
  locale: Locale,
): PostAudio | undefined {
  const entry = entries[`${locale}/${getCleanSlug(slug)}`];
  if (!entry) return undefined;
  return {
    src: entry.file,
    durationSeconds: entry.durationSeconds,
    bytes: entry.bytes,
  };
}

/** ISO 8601 duration for schema.org, e.g. PT11M42S. */
export function toIsoDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `PT${m}M${s}S`;
}

export function toMinutes(seconds: number): number {
  return Math.max(1, Math.round(seconds / 60));
}
