export const SITE_URL = "https://blog.guillermorodas.com";

/**
 * Podcast metadata for the iTunes tags in the RSS feeds.
 * An empty `ownerEmail` is left out of the feed until it is set.
 */
export const PODCAST = {
  // Square 3000 px covers generated by scripts/generate-og.mjs.
  cover: { en: "/og/podcast.png", es: "/og/es/podcast.png" },
  // Public in the feed; Apple Podcasts and Spotify use it to verify ownership.
  ownerEmail: "",
  category: "Technology",
  explicit: false,
};
